# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "42f9b3c401181a1f59ebe8da80cb579c"
application_url = "https://shipping-threshold-app-production.up.railway.app"
embedded = true
name = "Shipping Threshold Split Test"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_delivery_customizations,write_delivery_customizations,read_metaobjects,write_metaobjects,read_metaobject_definitions,write_metaobject_definitions"

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
uri = "https://shipping-threshold-app-production.up.railway.app/webhooks/app/uninstalled"
topics = [ "app/uninstalled" ]

[[webhooks.subscriptions]]
uri = "https://shipping-threshold-app-production.up.railway.app/webhooks/app/scopes_update"
topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://shipping-threshold-app-production.up.railway.app/api/auth" ]

[build]
automatically_update_urls_on_dev = true
